### ISSUE TITLE
有一个bug

### ISSUE THREAD

**Issue by xiahaifeng1995** [Blinkblade/Classifier_TensorRT#1]
![image](https://github.com/Blinkblade/Classifier_TensorRT/assets/32216515/4895eba2-4e5c-46e2-bc20-4f3367f5872f)
runtime要先声明，m_engine要后声明,不然在销毁的时候会报错

**Comment by Blinkblade** [comment]
你好，我研究了一下，你可能是觉得C++的成员变量销毁的顺序和声明顺序相反，而engine需要使用runtime反序列化模型，因此需要先销毁engine再销毁runtime。考虑到这一点，确实应该在声明engine前声明runtime，谢谢你的指正。
不过，这个程序应该不会出现这样的错误，因为这里使用了智能指针管理这两个变量，智能指针只有在失去所有引用的情况下才会自动销毁，因此无论按怎样的顺序销毁这两个变量他们都可以被正确销毁。
当然，也可能还有我理解不到位的地方，因为我对C++的细节掌握的不是很丰富，如有任何其他问题，也欢迎随时指出

**Comment by Blinkblade** [comment]
> ![image](https://private-user-images.githubusercontent.com/32216515/330747540-4895eba2-4e5c-46e2-bc20-4f3367f5872f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNDU4MzUsIm5iZiI6MTcxNjA0NTUzNSwicGF0aCI6Ii8zMjIxNjUxNS8zMzA3NDc1NDAtNDg5NWViYTItNGU1Yy00NmUyLWJjMjAtNGYzMzY3ZjU4NzJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDE1MTg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjN2Y4YjZlOGYwNTc5YzE4ZjExNWQ0ZjA3YjExOGNkYjRjNTM1YjFiMzRhMjMwNzg3YTQwMDRiZWFhNWE0OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ntg6jqbt-AFsBVtQ1tO-ZG90OfruFq2XMx4T6q_m13M) runtime要先声明，m_engine要后声明,不然在销毁的时候会报错

你好，我研究了一下，你可能是觉得C++的成员变量销毁的顺序和声明顺序相反，而engine需要使用runtime反序列化模型，因此需要先销毁engine再销毁runtime。考虑到这一点，确实应该在声明engine前声明runtime，谢谢你的指正。
不过，这个程序应该不会出现这样的错误，因为这里使用了智能指针管理这两个变量，智能指针只有在失去所有引用的情况下才会自动销毁，因此无论按怎样的顺序销毁这两个变量他们都可以被正确销毁。
当然，也可能还有我理解不到位的地方，因为我对C++的细节掌握的不是很丰富，如有任何其他问题，也欢迎随时指出
